# Generated by Django 3.1.2 on 2020-11-02 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='id_criterion',
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('id_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.criterion')),
                ('id_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.option')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PairsOfOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_option_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.option')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='criterion',
            name='id_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='id_model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.model'),
            preserve_default=False,
        ),
    ]
