# Generated by Django 3.1.2 on 2020-11-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201102_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='direction',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
