# Generated by Django 3.1.2 on 2020-11-02 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_criterion_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairsofoptions',
            name='winner_option',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_option', to='api.option'),
        ),
    ]
