# Generated by Django 3.1.2 on 2020-11-02 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201102_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairsofoptions',
            name='winner_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_option', to='api.option'),
        ),
    ]
