# Generated by Django 3.1.3 on 2020-11-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201102_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='user',
        ),
        migrations.AddField(
            model_name='model',
            name='number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
