# Generated by Django 3.1.3 on 2020-11-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201115_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsofoptions',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pairsofoptions',
            name='id_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.model'),
            preserve_default=False,
        ),
    ]
