# Generated by Django 3.1.3 on 2020-11-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201115_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='max',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
