# Generated by Django 3.1.3 on 2020-11-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_criterion_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
