# Generated by Django 3.1.3 on 2020-11-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_model_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairsofoptions',
            name='filename',
        ),
    ]
