# Generated by Django 3.1.3 on 2020-12-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_pairsofoptions_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='id_winner_option_many',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='id_winner_option_shnur',
            field=models.IntegerField(null=True),
        ),
    ]
