# Generated by Django 3.1.3 on 2020-12-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201208_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
