# Generated by Django 3.1.3 on 2020-12-10 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsofoptions',
            name='winner_option_many',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_option_many', to='api.option'),
        ),
    ]
