# Generated by Django 3.1.3 on 2020-12-10 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pairsofoptions_winner_option_many'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('answer', models.CharField(max_length=255)),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.model')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair', to='api.pairsofoptions')),
            ],
        ),
    ]
