# Generated by Django 3.1.3 on 2020-12-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_historyanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='time_answer_shnur',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='time_many',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='time_shnur',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
